stages:
  - test
  - build

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t my-docker-test-image ./BHCDatabase/

test:
  stage: test
  script:
    - docker run my-docker-test-image ./bin/rails t