# Base image:
FROM ruby:2.3.3

MAINTAINER David Brown <david_a_brown@mac.com

# Install dependencies
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

RUN mkdir -p RAILS_ROOT

# Set working directory, where the commands will be ran:
WORKDIR RAILS_ROOT

# Gems:
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock
RUN gem install bundler

ENV RAILS_ENV production

RUN bundle install --without development test

COPY config/puma.rb config/puma.rb

# Copy the main application.
COPY . .

RUN rake assets:precompile

EXPOSE 3000

# The default command that gets ran will be to start the Puma server.
CMD bundle exec puma -C config/puma.rb