version: "3"

services:
  db:
    image: postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile-production
    command: bundle exec puma -C config/puma.rb
    volumes:
      - assets:/var/www/bhc/public
    expose:
      - "3000"
    env_file:
      - ".env"
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    links:
      - app
    ports:
      - "81:80"
    volumes:
      - assets:/var/www/bhc/public

volumes:
  assets:
