version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    environment:
      POSTGRES_USER: 'bhc'
      POSTGRES_PASSWORD: 'bhc1234'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  website:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/bhc'
    env_file:
      - '.env'

volumes:
  postgres: