# Base image:
FROM ruby:2.3.3

MAINTAINER David Brown <david_a_brown@mac.com

# Install dependencies
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

# Set an environment variable where the Rails app is installed to inside of Docker image:
ENV RAILS_ROOT /var/www/bhc
RUN mkdir -p $RAILS_ROOT

# Set working directory, where the commands will be ran:
WORKDIR $RAILS_ROOT

# Gems:
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock
RUN gem install bundler

ENV RAILS_ENV test

RUN bundle install --without development production

COPY config/puma.rb config/puma.rb

# Copy the main application.
COPY . .